language: objective-c # force osx machines

os:
 - osx

env:
  global:
   - secure: qY6kU+hT5JteYRe456Pb+qQumenBBDOkzwYl+nQCxgCTYdX1krpGmnqox+GOSfC2CSWJDo58WGtydgKam/LDM1GTT1YY9Sv2kVUKGSUAzEQfj3PdUjHf+MvKOjhWq/KO9xkXQmYqmmjQs0vHKTjjtDVWiY+FQNpDDOSdLC8M8t4=
   - secure: GaMeHOZB4ro7G2jBS0sQdY6o73GCc4fOVujAtZSuRIG93OKDu4QH+EWPTYpyx5CRO/uFez60bSaBTTxixKAYHwvmm83ha0BnMKwp1aI/EdBMAgL2TrKxgroQgZqyCIKMKfm69vMLP9/Ui+rqP3MEnMo9AHVnfvWLQBHrzJdFpKs=
before_install:
 - date -u
 - uname -a
 - export BUILDTAG=`git describe --abbrev=0 --tags`
 - env | sort | grep -v ZIPPASSWORD | grep -v GITHUB_TOKEN

install:
 - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then echo "Should only be on OSX"; exit 1; fi
 - ./CI/travis.osx.install.deps.sh # it appears TRAVIS_OS_NAME is unset often, assume we're OSX if not linux

script:
 - ./build.remotetech2.sh

# Custom deploy
after_success:
 - ./CI/github.build.deploy.sh