language: objective-c # force osx machines

os:
 - osx

env:
  global:
   - secure: GgFneu4a+8lDlHilymkH5uqq5rEBv00lDfXS/eKC1dqL1qvbLAiwCF4GvW6j4lVLc0FXUAVWBBN0YxSENMsuY+UfR/3Yb9woPQI6dr+UTpH9JlX8vTuC7qIfprzZDS5fpx+1sZa7ZQfUaguD/lfW5DaR1kTB/MZ1F0+loJ+2nAY=
   - secure: TSr0YHzvrlYZzDBiMmeI3tY+v+SReBBs2OKf8C5M5gq/iPbyZFTBaG1yR9F5vNmbyQB3RMtw6EvmpsKCBFQXcP5THTXW8dsx728TrXICvq22FRveMVoivOY3M748GeQvtH0I1oCDiHGx5mU5ISwJ4VDPu2Nbk6kB/Ynb1WvmUh4=
before_install:
 - date -u
 - uname -a
 - export BUILDTAG=`git describe --abbrev=0 --tags`
 - env | sort | grep -v ZIPPASSWORD | grep -v GITHUB_TOKEN

install:
 - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then echo "Should only be on OSX"; exit 1; fi
 - ./CI/travis.osx.install.deps.sh # it appears TRAVIS_OS_NAME is unset often, assume we're OSX if not linux

script:
 - ./build.remotetech2.sh

# Custom deploy
after_success:
 - ./CI/github.build.deploy.sh